ZkAppTestVector {
            name: "complex_zkapp_command",
            zkapp_command: ZKAppCommand {
                fee_payer: FeePayer {
                    body: FeePayerBody {
                        public_key: PublicKey(CompressedPubKey::from_address("B62qpr9i4A2ARpoYEVVcB12zbZVkUgotwcyNMZaiUukaN742Ns4zU8m").unwrap()),
                        fee: 643111892413030582,
                        valid_until: None,
                        nonce: 1,
                    },
                    authorization: "7mWxjLYgbJUkZNcGouvhVj5tJ8yu9hoexb9ntvPK8t5LHqzmrL6QJjjKtf5SgmxB4QWkDw7qoMMbbNGtHVpsbJHPyTy2EzRQ".to_string(),
                },
                account_updates: vec![
// Account update 1
                    AccountUpdate {
                        body: AccountUpdateBody {
                            public_key: PublicKey(CompressedPubKey::from_address("B62qpr9i4A2ARpoYEVVcB12zbZVkUgotwcyNMZaiUukaN742Ns4zU8m").unwrap()),
                            token_id: Field(Fp::from_str("wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf").unwrap()),
                            update: Update {
                                app_state: vec![
                                    Some(Field(Fp::from_str("0").unwrap())),
                                    Some(Field(Fp::from_str("5111698368801117028806876834993178636129197759655207730310401195899573051515").unwrap())),
                                    Some(Field(Fp::from_str("28948022309329048855892746252171976963363056481941560715954676764349967630336").unwrap())),
                                    None,
                                    Some(Field(Fp::from_str("39431652223165594357492108665306").unwrap())),
                                    None,
                                    None,
                                    Some(Field(Fp::from_str("1309850520634805529570932182720").unwrap())),
                                ],
                                delegate: None,
                                verification_key: None,
                                permissions: Some(Permissions {
                                        edit_state: AuthRequired::Either,
                                        access: AuthRequired::Impossible,
                                        send: AuthRequired::Proof,
                                        receive: AuthRequired::Signature,
                                        set_delegate: AuthRequired::Either,
                                        set_permissions: AuthRequired::Impossible,
                                        set_verification_key: SetVerificationKey {
                                            auth: AuthRequired::None,
                                            txn_version: 72,
                                        },
                                        set_zkapp_uri: AuthRequired::Either,
                                        edit_action_state: AuthRequired::Proof,
                                        set_token_symbol: AuthRequired::None,
                                        increment_nonce: AuthRequired::Proof,
                                        set_voting_for: AuthRequired::Impossible,
                                        set_timing: AuthRequired::None,
                                    }),
                                zkapp_uri: None,
                                token_symbol: None,
                                timing: Some(TimingData {
                                        initial_minimum_balance: 344287641889,
                                        cliff_time: 2,
                                        cliff_amount: 1,
                                        vesting_period: 394775,
                                        vesting_increment: 193662179699,
                                    }),
                                voting_for: None,
                            },
                            balance_change: BalanceChange {
                                magnitude: 0,
                                sgn: 1,
                            },
                            increment_nonce: true,
                            events: Events {
                                data: vec![],
                                hash: Field::default(),
                            },
                            actions: Actions {
                                data: vec![],
                                hash: Field::default(),
                            },
                            call_data: Field(Fp::from_str("2445330178412509870353125666481945702803272446448831804008894538179830208472").unwrap()),
                            call_depth: 0,
                            preconditions: Preconditions {
                                network: NetworkPreconditions {
                                    snarked_ledger_hash: None,
                                    blockchain_length: None,
                                    min_window_density: None,
                                    total_currency: Some(RangeCondition { lower: 9627788837213698, upper: 0 }),
                                    global_slot_since_genesis: Some(RangeCondition { lower: 3733142, upper: 10732923 }),
                                    staking_epoch_data: EpochData {
                                        ledger: EpochLedger {
                                            hash: Some(Field(Fp::from_str("0").unwrap())),
                                            total_currency: Some(RangeCondition { lower: 16419439746915334, upper: 1304235577261289 }),
                                        },
                                        seed: None,
                                        start_checkpoint: None,
                                        lock_checkpoint: None,
                                        epoch_length: None,
                                    },
                                    next_epoch_data: EpochData {
                                        ledger: EpochLedger {
                                            hash: Some(Field(Fp::from_str("476617213929079578472390596483987346").unwrap())),
                                            total_currency: None,
                                        },
                                        seed: Some(Field(Fp::from_str("6550585206916319807276456733012627432234951109441771206867942148039046256882").unwrap())),
                                        start_checkpoint: None,
                                        lock_checkpoint: Some(Field(Fp::from_str("148").unwrap())),
                                        epoch_length: Some(RangeCondition { lower: 3775911251, upper: 2077609367 }),
                                    },
                                },
                                account: AccountPreconditions {
                                    balance: None,
                                    nonce: Some(RangeCondition { lower: 4294967295, upper: 4294967295 }),
                                    receipt_chain_hash: None,
                                    delegate: None,
                                    state: vec![
                                            None,
                                            Some(Field(Fp::from_str("28948022309329048855892746252171976963363056481941560715954676764349967630336").unwrap())),
                                            Some(Field(Fp::from_str("199661999234").unwrap())),
                                            Some(Field(Fp::from_str("28948022309329048855892746252171976963363056481941560715954676764349967630336").unwrap())),
                                            None,
                                            Some(Field(Fp::from_str("1").unwrap())),
                                            None,
                                            None,
                                        ],
                                    action_state: None,
                                    proved_state: None,
                                    is_new: None,
                                },
                                valid_while: None,
                            },
                            use_full_commitment: false,
                            implicit_account_creation_fee: true,
                            may_use_token: MayUseToken {
                                parents_own_token: false,
                                inherit_from_parent: false,
                            },
                            authorization_kind: AuthorizationKind {
                                is_signed: false,
                                is_proved: false,
                                verification_key_hash: Field(Fp::from_str("3392518251768960475377392625298437850623664973002200885669375116181514017494").unwrap()),
                            },
                        },
                        authorization: Authorization {
                            proof: None,
                            signature: None,
                        },
                    },
                ],
                memo: "E4YTaSy23qPfzsAxixYMsSrws5drrUksL1ch1bijh2FQNC7Rgubmm".to_string(),
            },
            network: NetworkId::MAINNET,
            expected_memo_hash: "0",
            expected_fee_payer_hash: "0",
            expected_account_updates_commitment: "0",
            expected_full_commitment: "0",
        }
